### ISSUE TITLE
Add Stubbing for Alert Creation

### ISSUE THREAD

**Issue by Aztrixs** [COS301-SE-2021/Kenzo-Workout-Suite#26]
Upon testing, I have discovered that without stubbing the actual alert create function, the tests will not run unless you are on the actual Karma browser, i.e. using just terminal.

To avoid such please add the following to all tests with alerts @JHFrost.

spyOn(alertController, "create").and.stub();

Where alertController is an instance of AlertController instantiated in your beforeEach. 

i.e 
` it('should fail to sign up an account as server is not responding.', async () => {
    spyOn(service, 'attemptSignUp').and.resolveTo(500);
    spyOn(component, "presentAlert").and.stub();
    await component.signUp().catch(error=>{
      expect(error).toEqual(new Error('Server is not responding.'));
    });
  });`

should be

` it('should fail to sign up an account as server is not responding.', async () => {
    spyOn(service, 'attemptSignUp').and.resolveTo(500);
    spyOn(alertController, "create").and.stub();
    spyOn(component, "presentAlert").and.stub();
    await component.signUp().catch(error=>{
      expect(error).toEqual(new Error('Server is not responding.'));
    });
  });`

**Comment by JHFrost** [comment]
Completed.
